print(2 + 3)
print(2 - 3)
print(2 * 3)
print(3 / 2)
print(3 ** 2)
print(2 % 3)
print(2 // 3)
print('Helena')
print('Troncoso')
print('España')
print('I am enjoying 30 days of python')
print(type (10))
print(type(9.8))
print(type(3.14))
print(type(4 - 4j))
print(type(['Helena', 'Troncoso', 'España']))
print(type ('Helena'))
print(type ('Troncoso'))
print(type('España'))
print(type ('8'))
print(type ('0.2'))
print(type ('-6i'))
print(type ('hello world'))
print(True) # Do I like chocolat? If I like it, then value is true 
print(False) # Do I like chocolat? If I don't like it, then value is false 
